### ISSUE TITLE
Rectangle

### ISSUE THREAD

**Issue by VictoriaRamirezCharles** [YauGoh/My.Maui.Responsive#1]
Hello, i have this error:

![image](https://github.com/YauGoh/My.Maui.Responsive/assets/38332341/a31f08d5-7687-42f3-a393-3e7ee5d1d945)

Can you help me?. When i try to import System.Drawing the size is not working:
![image](https://github.com/YauGoh/My.Maui.Responsive/assets/38332341/1cfed4be-2561-49ec-a669-a990a19d06d5)

**Comment by VictoriaRamirezCharles** [comment]
Resolve: #2.

**Comment by YauGoh** [comment]
Hi Victoria,

How did you go resolving that issue.  Sorry my attention has been focused on other things, I haven't been able to give this repo the attention it needs.  I orginaly started the project in my other repo - YauGoh/Xamarin.Responsive: Responsive layout for Xamarin Forms (github.com)<https://github.com/YauGoh/Xamarin.Responsive> which was based on Xamarin forms.

My.Maui.Responsive is currently based on an early release of Maui (before the official release).  I'm sure a lot of the Microsoft Libraries have changed quite a bit, I remember early struggles with many breaking changes with early alpha releases of Maui.

As you have sparked my interest in this package again, this weekend I intend to update to the latest version of Maui.

Thanks!
________________________________

**Comment by VictoriaRamirezCharles** [comment]
Thank you!!
